#=======================================服务器端口配置=======================================
server:
  port: 8088

#=======================================spring配置=======================================
spring:
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/templates/
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://db:3307/pump?serverTimezone=UTC&useUnicode=true&haracterEncoding=utf8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      #最大活跃数
      max-active: 20
      #初始化数量
      initial-size: 1
      #最大连接等待超时时间
      max-wait: 60000
      #打开PSCache 并且指定每个连接的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      #通过connectionProperties属性来打开mergeSql功能  慢sql记录
      #connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      minIdle: 1
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: select 1 from dual
      #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
      filters: stat, wall, log4j
      time-between-connect-error-millis: 10000
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  servlet:
    multipart:
      enabled: true #开启文件上传
      max-file-size: 10MB #最大文件10mb
#  security:
#    user:
#      name: 1024
#      password: 1024
#  mvc:
#    view:
#      prefix: WEB-INF/jsp
#      suffix: .jsp

#=======================================redis配置=======================================
#  redis:
#    host: localhost
#    port: 6379
#    database: 1
#    timeout: 5000
#    pool:
#      max-active: 8
#      max-idle: 500
#      min-idle: 0
#      max-wait: -1

#=======================================mybatis配置=======================================
mybatis:
  mapper-locations: classpath*:com.xuwx.pump.mbg.mapper/*Mapper*.xml
  type-aliases-package:  com.xuwx.pump.mbg.mapper

#=======================================MinIo配置=======================================
# MinIO对象存储相关配置
minio:
  endpoint: http://172.31.205.169:9090 #MinIO服务所在地址  47.105.181.206公网
  bucketName: pump #存储桶名称
  accessKey: minioadmin #访问的key
  secretKey: minioadmin #访问的秘钥

