package com.xuwx.pump.mbg.mapper;

import com.xuwx.pump.mbg.model.SysQuartzJob;
import com.xuwx.pump.mbg.model.SysQuartzJobExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysQuartzJobMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    int countByExample(SysQuartzJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    int deleteByExample(SysQuartzJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    int deleteByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    int insert(SysQuartzJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    int insertSelective(SysQuartzJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    List<SysQuartzJob> selectByExample(SysQuartzJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    SysQuartzJob selectByPrimaryKey(Long jobId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    int updateByExampleSelective(@Param("record") SysQuartzJob record, @Param("example") SysQuartzJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    int updateByExample(@Param("record") SysQuartzJob record, @Param("example") SysQuartzJobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    int updateByPrimaryKeySelective(SysQuartzJob record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    int updateByPrimaryKey(SysQuartzJob record);
}