package com.xuwx.pump.mbg.model;

import java.io.Serializable;

public class SysQuartzJob implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_quartz_job.job_id
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    private Long jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_quartz_job.job_name
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_quartz_job.job_group
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    private String jobGroup;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_quartz_job.job_status
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    private String jobStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_quartz_job.audit_status
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    private String auditStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_quartz_job.cron_expression
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    private String cronExpression;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_quartz_job.quartz_class
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    private String quartzClass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_quartz_job.description
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_quartz_job.job_id
     *
     * @return the value of sys_quartz_job.job_id
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_quartz_job.job_id
     *
     * @param jobId the value for sys_quartz_job.job_id
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_quartz_job.job_name
     *
     * @return the value of sys_quartz_job.job_name
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_quartz_job.job_name
     *
     * @param jobName the value for sys_quartz_job.job_name
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public void setJobName(String jobName) {
        this.jobName = jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_quartz_job.job_group
     *
     * @return the value of sys_quartz_job.job_group
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public String getJobGroup() {
        return jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_quartz_job.job_group
     *
     * @param jobGroup the value for sys_quartz_job.job_group
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public void setJobGroup(String jobGroup) {
        this.jobGroup = jobGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_quartz_job.job_status
     *
     * @return the value of sys_quartz_job.job_status
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public String getJobStatus() {
        return jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_quartz_job.job_status
     *
     * @param jobStatus the value for sys_quartz_job.job_status
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public void setJobStatus(String jobStatus) {
        this.jobStatus = jobStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_quartz_job.audit_status
     *
     * @return the value of sys_quartz_job.audit_status
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public String getAuditStatus() {
        return auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_quartz_job.audit_status
     *
     * @param auditStatus the value for sys_quartz_job.audit_status
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public void setAuditStatus(String auditStatus) {
        this.auditStatus = auditStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_quartz_job.cron_expression
     *
     * @return the value of sys_quartz_job.cron_expression
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public String getCronExpression() {
        return cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_quartz_job.cron_expression
     *
     * @param cronExpression the value for sys_quartz_job.cron_expression
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public void setCronExpression(String cronExpression) {
        this.cronExpression = cronExpression;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_quartz_job.quartz_class
     *
     * @return the value of sys_quartz_job.quartz_class
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public String getQuartzClass() {
        return quartzClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_quartz_job.quartz_class
     *
     * @param quartzClass the value for sys_quartz_job.quartz_class
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public void setQuartzClass(String quartzClass) {
        this.quartzClass = quartzClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_quartz_job.description
     *
     * @return the value of sys_quartz_job.description
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_quartz_job.description
     *
     * @param description the value for sys_quartz_job.description
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_quartz_job
     *
     * @mbggenerated Tue Jul 14 10:57:27 GMT+08:00 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", jobId=").append(jobId);
        sb.append(", jobName=").append(jobName);
        sb.append(", jobGroup=").append(jobGroup);
        sb.append(", jobStatus=").append(jobStatus);
        sb.append(", auditStatus=").append(auditStatus);
        sb.append(", cronExpression=").append(cronExpression);
        sb.append(", quartzClass=").append(quartzClass);
        sb.append(", description=").append(description);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}